# permissions for end users to edit imagescanadapterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagescanadapterconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vulnerability-adapter
    app.kubernetes.io/part-of: vulnerability-adapter
    app.kubernetes.io/managed-by: kustomize
  name: imagescanadapterconfig-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs/status
  verbs:
  - get
