# permissions for end users to view imagescanadapterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: imagescanadapterconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vulnerability-adapter
    app.kubernetes.io/part-of: vulnerability-adapter
    app.kubernetes.io/managed-by: kustomize
  name: imagescanadapterconfig-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs/status
  verbs:
  - get
