apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vulnerability-adapter.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ImageScanAdapterConfig is the Schema for the imagescanadapterconfigs
        API
      displayName: Image Scan Adapter Config
      kind: ImageScanAdapterConfig
      name: imagescanadapterconfigs.my.domain
      version: v1alpha1
  description: vulnerability adapter
  displayName: vulnerability-adapter
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - none
  links:
  - name: Vulnerability Adapter
    url: https://vulnerability-adapter.domain
  maintainers:
  - email: kushal.beniwal@nirmata.com
    name: kushal
  maturity: alpha
  provider:
    name: na
  version: 0.0.0
