apiVersion: my.domain/v1alpha1
kind: ImageScanAdapterConfig
metadata:
  labels:
    app.kubernetes.io/name: imagescanadapterconfig
    app.kubernetes.io/instance: imagescanadapterconfig-sample
    app.kubernetes.io/part-of: vulnerability-adapter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vulnerability-adapter
  name: imagescanadapterconfig-sample
spec:
  # TODO(user): Add fields here
