# Default values for vulnerability-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the name of the chart
nameOverride:

# -- Override the expanded name of the chart
fullnameOverride:

severity: []
policyReportPrefix: image-scan
scannerEngine: grype
outputFormat: PolicyReport
scanInterval: 10m
scanAll: false
namespaces: []

rbac:
  # -- Enable RBAC resources creation
  create: true

  serviceAccount:
    # -- Service account name, you MUST provide one when `rbac.create` is set to `false`
    name: kushal-vuln-service-account

image:
  # -- Image repository
  repository: ghcr.io/kbeniwal/vulnerability-adapter
  # -- Image pull policy
  pullPolicy: Always
  # -- Image tag (defaults to chart app version)
  tag: v0.1.0-pr.1
  # -- Image pull secrets
  imagePullSecrets: []
