{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vulnerability-adapter.fullname" . }}
  labels:
    {{- include "vulnerability-adapter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - my.domain
  resources:
  - imagescanadapterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  verbs:
  - get
  - list
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulnerability-adapter.serviceAccountName" . }}
  labels:
    {{- include "vulnerability-adapter.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vulnerability-adapter.fullname" . }}
  labels:
    {{- include "vulnerability-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vulnerability-adapter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "vulnerability-adapter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
