name: Release

on:
  push:

env:
  IMG_REPOSITORY : ghcr.io/kbeniwal/vulnerability-adapter

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go 
        uses: actions/setup-go@v1
        with:
          go-version-file: go.mod
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create charts tmp directory
        run: |
          set -e
          mkdir charts-tmp
          cp -a charts/vulnerability-adapter charts-tmp/vulnerability-adapter
      - name: Package charts
        run: |
          set -e
          for dir in `find charts-tmp -maxdepth 1 -mindepth 1 -type d -print`; do
            chart=${dir##*/}
            echo "Found chart: ${chart}"
            helm package charts-tmp/${chart} --version v0.1.0-pr.1 --app-version v0.1.0-pr.1 --destination .cr-release-packages
          done
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@main
        with:
          charts_dir: .helm-dist
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"